export const theme = {
  colors: {
    primary: "#2984B9",
    tableHeaderBorder: "#23688F",
    error: "#E47474",
    ribbonTitle: "#fff",
    secondary: "#B8BCC6",
    default: "#333758",
    success: "#77C998",
    text: "#434343",
    textGray: "#999",
    textLight: "#eee",
    bluishGray: "#f7f7fa",
    borderColorDark: "#DEDEDE",
    tableElementBorder: "rgba(0,0,0,0.2)",
    rowIconColor: "rgba(0,0,0,0.5)",
    rowEditBgColor: "#F0F7F3",
    rowFontColor: "rgba(51, 51, 51, 0.9)",
    rowBorderColor: " rgba(123, 131, 128, 0.3)",
    iconBorderColor: "#444444",
    sideNavText: "#656565",
    sideNavBgColor: "#10163D",

    errorTitle: "#ff0000",
    textRed: "#ff0000",
    buttonGrey: "#F0F0F4",
    login: "#B58B00",
    circlegreen: "#32CD32",
    classic: "#89CFF0",
    classicCircle: "#6495ED",
    gold: "#F6BE00",
    goldCircle: "#B58B09",
    premium: "#F88379",
    premiumCircle: "#50C878",
    bgcolor: "#F5F5F5",
    white: "white",
    navy: "#27445C",
  },
  dimensions: {
    borderRadius: "4px",
    tableRowGap: "2px",
  },
  center: {
    display: "inline-flex",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  left: {
    display: "inline-flex",
    alignContent: "left",
    alignItems: "left",
    justifyContent: "left",
  },
  leftcenter: {
    display: "flex",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonstyle: {
    backgroundColor: "#B58B00",
    padding: "8px 106px",
    fontSize: "18px",
    borderRadius: "70px",
  },

  dropstyle: { height: "40px", width: "225px", border: "none" },
  dropstyleproperty: { height: "40px", width: "190px", border: "none" },
  textstyle: {
    fontSize: "14px",
    fontWeight: "bold",
    fontFamily: "Arial",
    color: "#656565",
  },
  headstyle: {
    fontSize: "12px",
    fontWeight: "bold",
    fontFamily: "",
    color: "#999",
  },
  boldstyle: {
    fontSize: "16px",
    fontWeight: "bold",
    fontFamily: "",
    opacity: ".8",
  },
  bodystyle: {
    fontSize: "13px",
    fontWeight: "",
    fontFamily: "",
    color: "grey",
  },
  datestyle: {
    fontSize: "12px",
    fontWeight: "",
    fontFamily: "",
    color: "#eee",
  },
  iconstyle: {
    position: "relative",
    height: "18px",
  },
};
